# CloudCannon configuration for 柳川内科医院
# https://cloudcannon.com/documentation/

timezone: Asia/Tokyo
source: ""
output: ""

paths:
  static: ""
  uploads: images

markdown:
  engine: commonmark
  options: {}

collections_config:
  pages:
    path: ""
    url: "/[slug]/"
    glob: "**/*.html"
    name: "Pages"
    icon: wysiwyg
    output: true
    _enabled_editors:
      - visual
      - code

_editables:
  content:
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    horizontalrule: true
    blockquote: true
  text:
    bold: true
    italic: true
    link: true
